- name: install maven
  hosts: production
  tasks:
   - name: Fix 'support_tools' permissions
     become: True
     become_user: root
     file:
       path: /var/run/docker.sock
       owner: root
       group: docker
       mode: '0777'
   - name: create a table in mysqlDB
     command: docker exec -it mysql1 mysql -uroot -pnewpassword exchangerate --skip-column-names --execute "create table exchange_rate(id INT AUTO_INCREMENT PRIMARY KEY,dollaramount varchar(80),datetimeval DATETIME );"
